### ISSUE TITLE
Code elements rendering with serif font

### ISSUE THREAD

**Issue by robertandrews** [sergey900553/obsidian_githublike_theme#1]
<img width="668" alt="Screenshot 2022-04-19 at 16 08 16" src="https://user-images.githubusercontent.com/3158787/164035807-d2fc72fc-ed5b-4ec1-ba22-5ceab943c46a.png">

**Comment by Eagle-251** [comment]
It seems that this line is overidding whatever Monospace font you set in Obsidian's settings:
https://github.com/sergey900553/obsidian_githublike_theme/blob/bde260f61e3c62eba7772dad1d144610d9de6111/obsidian.css#L73

**Comment by sergey900553** [comment]
I fixed the font display. The obsidian settings seem to work if the theme
doesn't specify a font
