### ISSUE TITLE
New update completely broke edit mode

### ISSUE THREAD

**Issue by Xiarno** [sergey900553/obsidian_githublike_theme#3]
Cannot edit any notes anymore because of how broken it is.
Everything I write goes vertical.
![image](https://user-images.githubusercontent.com/24660485/195698079-5c153412-ef53-4d1d-82b2-2dc7adaa9471.png)

**Comment by sergey900553** [comment]
Fix it, try reinstalling the theme (not updating)

**Comment by Xiarno** [comment]
Fixed!
