### ISSUE TITLE
Export to PDF formatting issues (same as issue #2)

### ISSUE THREAD

**Issue by ruperlopez** [sergey900553/obsidian_githublike_theme#5]
I reinstalled the theme and the problem persists.

When I export as a PDF through obsidian, bold text appears white in the PDF file created and the text it can't be seen.

**Comment by HwiYeongLEE** [comment]
Did you fixed it? Still getting the same problem here

**Comment by hwi0lee** [comment]
I fixed it by adding

```css
strong,
b {
    color: #000 !important;
}
```

at the end of the theme css file.
